/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "#000000",
          50: "#eef5ff",
          100: "#d9eaff",
          600: "#2563eb",
          700: "#1d4ed8",
          800: "#1e3a8a",
        },
        "accent-teal": "#0f766e",
        "accent-pink": "#db2777",
        "accent-purple": "#7c3aed",
        "on-primary-fixed-variant": "#3f465c",
        "outline-variant": "#c6c6cd",
        "on-background": "#0b1c30",
        "on-secondary": "#ffffff",
        "surface-container": "#e5eeff",
        "tertiary-container": "#2f1500",
        error: "#ba1a1a",
        "inverse-primary": "#bec6e0",
        outline: "#76777d",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#005049",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#d3e4fe",
        "secondary-container": "#86f2e4",
        "secondary-fixed": "#89f5e7",
        background: "#f8f9ff",
        "on-tertiary-container": "#c76c00",
        "on-tertiary-fixed": "#2f1500",
        "on-primary-fixed": "#131b2e",
        "surface-tint": "#565e74",
        "on-surface-variant": "#45464d",
        "surface-dim": "#cbdbf5",
        surface: "#f8f9ff",
        "on-secondary-container": "#006f66",
        "on-secondary-fixed": "#00201d",
        "on-error": "#ffffff",
        tertiary: "#000000",
        "primary-container": "#131b2e",
        "secondary-fixed-dim": "#6bd8cb",
        "on-primary-container": "#7c839b",
        "primary-fixed": "#dae2fd",
        "surface-bright": "#f8f9ff",
        secondary: "#006a61",
        "on-surface": "#0b1c30",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#bec6e0",
        "surface-container-high": "#dce9ff",
        "surface-container-low": "#eff4ff",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "surface-variant": "#d3e4fe",
        "on-tertiary-fixed-variant": "#6e3900",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffb77d",
        "inverse-surface": "#213145",
        "tertiary-fixed": "#ffdcc3",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "grid-margin-desktop": "80px",
        "section-gap-mobile": "64px",
        base: "8px",
        "container-max-width": "1280px",
        "grid-gutter": "24px",
        "section-gap-desktop": "120px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Public Sans", "sans-serif"],
        "display-lg": ["Public Sans", "sans-serif"],
        "headline-lg-mobile": ["Public Sans", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md": ["Public Sans", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
      },
      maxWidth: {
        "container-max-width": "1280px",
      },
    },
  },
  plugins: [],
};
